//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for QuestionType.
const (
	MultipleChoice QuestionType = "multiple_choice"
	SingleChoice   QuestionType = "single_choice"
	Text           QuestionType = "text"
)

// Valid indicates whether the value is a known member of the QuestionType enum.
func (e QuestionType) Valid() bool {
	switch e {
	case MultipleChoice:
		return true
	case SingleChoice:
		return true
	case Text:
		return true
	default:
		return false
	}
}

// Answer defines model for Answer.
type Answer struct {
	// QuestionId ID вопроса
	QuestionId openapi_types.UUID `json:"question_id"`

	// Value Для text: строка.
	// Для single_choice: строка с выбранным вариантом.
	// Для multiple_choice: массив строк.
	Value Answer_Value `json:"value"`
}

// AnswerValue0 defines model for .
type AnswerValue0 = string

// AnswerValue1 defines model for .
type AnswerValue1 = []string

// Answer_Value Для text: строка.
// Для single_choice: строка с выбранным вариантом.
// Для multiple_choice: массив строк.
type Answer_Value struct {
	union json.RawMessage
}

// AnswerRecord defines model for AnswerRecord.
type AnswerRecord struct {
	Answers     []Answer           `json:"answers"`
	Id          openapi_types.UUID `json:"id"`
	Respondent  *string            `json:"respondent,omitempty"`
	SubmittedAt time.Time          `json:"submitted_at"`
}

// Error defines model for Error.
type Error struct {
	Details *string `json:"details,omitempty"`
	Error   string  `json:"error"`
}

// Question defines model for Question.
type Question struct {
	Id openapi_types.UUID `json:"id"`

	// Options Варианты ответа для choice-типов
	Options  *[]string `json:"options,omitempty"`
	Required *bool     `json:"required,omitempty"`
	Text     string    `json:"text"`

	// Type Тип вопроса
	Type QuestionType `json:"type"`
}

// QuestionType Тип вопроса
type QuestionType string

// SubmitAnswersRequest defines model for SubmitAnswersRequest.
type SubmitAnswersRequest struct {
	Answers []Answer `json:"answers"`

	// Respondent Имя респондента (опционально)
	Respondent *string `json:"respondent,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// SubmitAnswersJSONRequestBody defines body for SubmitAnswers for application/json ContentType.
type SubmitAnswersJSONRequestBody = SubmitAnswersRequest

// AsAnswerValue0 returns the union data inside the Answer_Value as a AnswerValue0
func (t Answer_Value) AsAnswerValue0() (AnswerValue0, error) {
	var body AnswerValue0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAnswerValue0 overwrites any union data inside the Answer_Value as the provided AnswerValue0
func (t *Answer_Value) FromAnswerValue0(v AnswerValue0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAnswerValue0 performs a merge with any union data inside the Answer_Value, using the provided AnswerValue0
func (t *Answer_Value) MergeAnswerValue0(v AnswerValue0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAnswerValue1 returns the union data inside the Answer_Value as a AnswerValue1
func (t Answer_Value) AsAnswerValue1() (AnswerValue1, error) {
	var body AnswerValue1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAnswerValue1 overwrites any union data inside the Answer_Value as the provided AnswerValue1
func (t *Answer_Value) FromAnswerValue1(v AnswerValue1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAnswerValue1 performs a merge with any union data inside the Answer_Value, using the provided AnswerValue1
func (t *Answer_Value) MergeAnswerValue1(v AnswerValue1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Answer_Value) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Answer_Value) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Принять и сохранить ответы пользователя
	// (POST /answers)
	SubmitAnswers(w http.ResponseWriter, r *http.Request)
	// Получить список вопросов анкеты
	// (GET /questions)
	GetQuestions(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// SubmitAnswers operation middleware
func (siw *ServerInterfaceWrapper) SubmitAnswers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitAnswers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetQuestions operation middleware
func (siw *ServerInterfaceWrapper) GetQuestions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetQuestions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/answers", wrapper.SubmitAnswers)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/questions", wrapper.GetQuestions)

	return m
}
